### ISSUE TITLE
Facing an issues with PolyLine

### ISSUE THREAD

**Issue by ashishke2m** [raphaelmor/Polyline#48]
[!] Unable to satisfy the following requirements:

- `Polyline (~> 4.2.0)` required by `Podfile`
- `Polyline (= 4.1.1)` required by `MapboxDirections.swift (0.12.0)`

**Comment by 1ec5** [comment]
MapboxDirections.swift currently requires Polyline v4.1.1 because it’s still written in Swift 3.2, whereas Polyline v4.2.0 is written in Swift 4. Does your Podfile require v4.2.0 because it’s written in Swift 4?

**Comment by ashishke2m** [comment]
My project is converted into Swift 4.0 and I updated a version of mapboxNavigation too.Now, what will be the solution to Use a swift 4.0 throughout SDK?

**Comment by 1ec5** [comment]
The Mapbox Navigation SDK is about to migrate to Swift 4 and upgrade to Polyline v4.2.0+: mapbox/mapbox-navigation-ios#663. The issue you’re running into will go away as soon as that happens, without any changes to this library. Since there aren’t any Polyline-specific changes to make, I’ll close this issue, but please keep an eye on the navigation SDK repository for updates.
