### ISSUE TITLE
"Cannot find type 'LocationCoordinate2D' in scope"

### ISSUE THREAD

**Issue by Av3r3tt** [raphaelmor/Polyline#73]
Just tried to manually drag Polyline.swift into my project and I get a list of errors based in the fact that

> Cannot find type 'LocationCoordinate2D' in scope

Are LocationCoordinate2D the same as CLLocationCoordinate2D? Is it just defined as an alias outside Polyline.swift?

Thanks for any help.

**Comment by 1ec5** [comment]
As of #55, this project uses `LocationCoordinate2D` instead of `CLLocationCoordinate2D` so that it compiles on Linux, which doesn’t have Core Location. On Apple platforms, which have Core Location, `LocationCoordinate2D` is indeed just a type alias for `CLLocationCoordinate2D`. The definition is located in a separate file:

https://github.com/raphaelmor/Polyline/blob/36f7b1222aaf8fa741d0d179c12e186998d97f42/Sources/Polyline/CoreLocation.swift#L34

This project may not be limited to these two files in the future, so consider using a dependency manager such as Swift Package Manager (built into Xcode) to pull in Polyline more reliably.
